from django.http import HttpResponse
import os
import psycopg2 as psycopg

# Create your views here.
def init(request, table_name='ex00_movies'):
	try:
		with psycopg.connect(
			f'''
			dbname={os.getenv('dbname')}
			user={os.getenv('user')}
			password={os.getenv('password')}
			host={os.getenv('host')}
			port={os.getenv('port')}
			'''
		) as conn:
			try:
				with conn.cursor() as cur:
					# cur.execute("SELECT version();")
					# db_version = cur.fetchone()
					# print (db_version, file=sys.stderr)
			
					cur.execute(
						f'''
						CREATE TABLE {table_name} (
							title VARCHAR(64) NOT NULL UNIQUE,
							episode_nb BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
							opening_crawl TEXT,
							director VARCHAR(32) NOT NULL,
							procuder VARCHAR(128) NOT NULL,
							release_date DATE NOT NULL
						);
						''')
					
					conn.commit()
					return HttpResponse('OK')

			except psycopg.Error as e:
				conn.rollback()
				return HttpResponse(f'Error: {e}')

			# finally:
			# 	if conn:
					# conn.close()
					# return HttpResponse('OK')
			# print ("hello world", file=sys.stderr)
	except psycopg.OperationalError:
		return HttpResponse("Error: can not connect database")
